#-----------------#
# Datapack Manger #
#   by kruthers   #
#-----------------#
# datapack_world - the world where the datapacks folder is
datapack_world: world
brodcast_lag: false
auth:
  ssh:
    password: ''
  normal:
    username: 'username'
    password: 'password'
  token:
    token: 'token'
messages:
  setup: '<light_purple>[Git] </light_purple><gold><name> Is setting up the datapack folder.</gold>'
  pull: '<light_purple>[Git] </light_purple><gold><user> Is pulling the datapack folder from github.</gold>'
  lag_warning: '<dark_red>[Warning] The datapack folder is getting updated, prepair for lag</dark_red>'
