# --------------------------- #
# Datapack manager for github #
#         by kruthers         #
# --------------------------- #
# invalid_permission - the invalid permissions message
# date_format - the format that the date will be stored in inside the data.yml file
# github.login_method - defines how it will log into github,
#     login - username & password | ssh - use an ssh key | none - no login method
# github.url - used to define the url that the repo is hosted at must be a ssh link
# github.auto_pull - will attempt to pull the data pack repo on a regular bases
# github.pull_on_start - this will make the plugin update the datapack on start
# authentication - used for defining the values use if you want to login to github
# authentication.use_passphrase - says if a passphrase is need when using ssh (not recommend)
# --------------------------- #
invalid_permission: "&4Sorry you cant run that command"
date_format: "yyyy/MM/dd HH:mm:ss"
github:
  login_method: none
  url: ssh://example.com/repo.git
  auto_pull: false
  pull_on_start: false
authentication:
  username: username
  password: password
  ssh_passphrase: passphrase
  use_passphrase: false