name: $name
version: $version
main: com.kruthers.datapackmanager.DatapackManager
api-version: 1.19
author: kruthers
description: $description
permissions:
  datapackmanager.reload:
    description: Used to reload the plugin
    default: op
  datapackmanager.core:
    description: Access to the default command
    default: true
  datapackmanager.git:
    description: Get basic pull access to the git datapacks
    default: op
  datapackmanager.git.setup:
    description: Givs you permission to setup/reset the github repo
    default: op
  datapackmanager.notify:
    description: Notifies you of when an update is happing
    default: op
