name: DatapackManager
version: ${project.version}
main: com.kruthers.datapackmanager.DatapackManager
authors: [kruthers]
description: Datapack Github Manager
api-version: 1.15
commands:
  datapackmanager:
    usage: /<command> [version|setup|reload] [confirm]
    description: Core command for datapack manager
    permission: datapackmanager.default
  gitpull:
    usage: /<command>
    description: Pull into your datapack folder
    permission: datapackmanager.pull
permissions:
  datapackmanager.default:
    description: Used by the core command
    default: true
  datapackmanager.reload:
    description: Used to reload the plugin
    default: op
  datapackmanager.setup:
    description: Used to setup the datapacks folder
    default: op
  datapackmanager.pull:
    description: Used to pull into the datapacks folder
    default: op
  datapackmanager.broadcast:
    description: used to broadcast messages about datapack pulls
    default: op